budget/urls.py
from django.urls import path

from budget import views

app_name = "budget"
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    # Accounts
    path("accounts/", views.AccountList.as_view(), name="account-list"),
    path("accounts/add/", views.AccountCreate.as_view(), name="account-add"),
    path("accounts/<int:pk>/", views.AccountView.as_view(), name="account-detail"),
    path(
        "accounts/<int:pk>/update/",
        views.AccountUpdate.as_view(),
        name="account-update",
    ),
    path(
        "accounts/<int:pk>/delete/",
        views.AccountDelete.as_view(),
        name="account-delete",
    ),
    # Backups
    path("backups/", views.BackupList.as_view(), name="backup-list"),
    path("backups/add/", views.BackupUpload.as_view(), name="backup-add"),
    path("backups/addnew/", views.BackupCreateNew.as_view(), name="backup-addnew"),
    path(
        "backups/purge_confirm/",
        views.BackupPurgeAllConfirm.as_view(),
        name="backup-purge-confirm",
    ),
    path("backups/purge/", views.BackupPurgeAll.as_view(), name="backup-purge"),
    path("backups/<int:pk>/", views.BackupView.as_view(), name="backup-detail"),
    path(
        "backups/<int:pk>/download/",
        views.BackupDownload.as_view(),
        name="backup-download",
    ),
    path(
        "backups/<int:pk>/delete/", views.BackupDelete.as_view(), name="backup-delete"
    ),
    path(
        "backups/<int:pk>/restore/",
        views.BackupRestore.as_view(),
        name="backup-restore",
    ),
    # Uploads
    path("uploads/", views.UploadList.as_view(), name="upload-list"),
    path("uploads/add/", views.UploadCreate.as_view(), name="upload-add"),
    path("uploads/<int:pk>/", views.UploadView.as_view(), name="upload-detail"),
    path(
        "uploads/<int:pk>/delete/", views.UploadDelete.as_view(), name="upload-delete"
    ),
    # Classes
    path("classes/<int:pk>/", views.ClassView.as_view(), name="class-detail"),
    path(
        "classes/<int:pk>/update/", views.BudgetUpdate.as_view(), name="budget-update"
    ),
    # Categories
    path("categories/add/", views.CategoryCreate.as_view(), name="category-add"),
    path("categories/<int:pk>/", views.CategoryView.as_view(), name="category-detail"),
    path(
        "categories/<int:pk>/update/",
        views.CategoryUpdate.as_view(),
        name="category-update",
    ),
    path(
        "categories/<int:pk>/delete/",
        views.CategoryDelete.as_view(),
        name="category-delete",
    ),
    # Patterns
    path("patterns/", views.PatternList.as_view(), name="pattern-list"),
    path("patterns/add/", views.PatternCreate.as_view(), name="pattern-add"),
    path("patterns/<int:pk>/", views.PatternView.as_view(), name="pattern-detail"),
    path(
        "patterns/<int:pk>/update/",
        views.PatternUpdate.as_view(),
        name="pattern-update",
    ),
    path(
        "patterns/<int:pk>/delete/",
        views.PatternDelete.as_view(),
        name="pattern-delete",
    ),
    path("patterns/classify/", views.PatternClassify.as_view(), name="classify"),
    path("patterns/declassify/", views.PatternDeclassify.as_view(), name="declassify"),
    path(
        "patterns/upload/",
        views.PatternBulkUpdate.as_view(),
        name="pattern-bulk-update",
    ),
    # Transactions
    path("transactions/", views.TransactionList.as_view(), name="transaction-list"),
    path(
        "transactions/<int:pk>/",
        views.TransactionView.as_view(),
        name="transaction-detail",
    ),
    path(
        "transactions/<int:pk>/delete/",
        views.TransactionDelete.as_view(),
        name="transaction-delete",
    ),
]

debt/urls.py
from django.urls import path

from debt import views

app_name = "debt"
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    # Accounts
    path("accounts/", views.AccountList.as_view(), name="account-list"),
    path("accounts/add/", views.AccountCreate.as_view(), name="account-add"),
    path("accounts/<int:pk>/", views.AccountView.as_view(), name="account-detail"),
    path(
        "accounts/<int:pk>/update/",
        views.AccountUpdate.as_view(),
        name="account-update",
    ),
    path(
        "accounts/<int:pk>/delete/",
        views.AccountDelete.as_view(),
        name="account-delete",
    ),
    path(
        "accounts/upload/",
        views.CreditLineBulkUpdate.as_view(),
        name="creditline-bulk-update",
    ),
    # Statements
    path("statements/add/", views.StatementCreate.as_view(), name="statement-add"),
    path(
        "statements/download/",
        views.StatementBulkDownload.as_view(),
        name="statement-download",
    ),
    path(
        "statements/upload/",
        views.StatementBulkUpdate.as_view(),
        name="statement-bulk-update",
    ),
    path(
        "statements/delete/confirm",
        views.StatementBulkDeleteConfirm.as_view(),
        name="statement-bulk-delete-confirm",
    ),
    path(
        "statements/delete/",
        views.StatementBulkDelete.as_view(),
        name="statement-bulk-delete",
    ),
    path(
        "statements/<int:pk>/update/",
        views.StatementUpdate.as_view(),
        name="statement-update",
    ),
    path(
        "statements/<int:pk>/delete/",
        views.StatementDelete.as_view(),
        name="statement-delete",
    ),
    # Summaries
    path("summaries/debt", views.DebtSummary.as_view(), name="debt-summary"),
]

simplefi/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(url="budget/", permanent=False), name="index"),
    path("auth/", include("django_registration.backends.activation.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("budget/", include("budget.urls")),
    path("debt/", include("debt.urls")),
    path("admin/", admin.site.urls),
]

debt/forms.py
from django import forms


class CreditLineBulkUpdateForm(forms.Form):
    csv = forms.FileField()


class StatementBulkUpdateForm(forms.Form):
    csv = forms.FileField()

debt/views.py
import csv
import datetime
import os
import tempfile
from typing import TYPE_CHECKING, Any, Callable, Dict, List, Mapping, Tuple, Union

import pandas as pd
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import FieldError
from django.db.models import ForeignKey
from django.http import FileResponse, HttpResponseRedirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django_tables2 import Column
from django_tables2.views import SingleTableView

from debt import forms, models, tables
from debt.utils import DebtSummaryTable, get_debt_budget

if TYPE_CHECKING:
    from django.db.models import Model
    from django.db.models.query import QuerySet
    from django.http import HttpRequest


class Index(LoginRequiredMixin, generic.TemplateView):
    template_name = "debt/index.html"


class AuthQuerySetMixin:
    """A mixin for generic display views for user data.

    Restricts the queryset to user-associated data only.
    """

    model = None  # type: Union[Model, None]
    request = None  # type: Union[HttpRequest, None]

    def get_queryset(self) -> "QuerySet":
        return self.model.objects.filter(user=self.request.user)


class AuthCreateFormMixin:
    """A mixin for generic create views for user data.

    Automatically assigns the logged-in user to the 'user' field of the
    model.
    """

    request = None  # type: Union[HttpRequest, None]

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class AuthForeignKeyMixin:
    """A mixin for generic edit views to protect other users' data.

    Restricts the queryset for all foreign key fields to user-
    associated data only.
    """

    model = None  # type: Union[Model, None]
    request = None  # type: Union[HttpRequest, None]

    def get_context_data(self, **kwargs) -> Dict:
        context = super().get_context_data(**kwargs)
        if "form" in context and hasattr(context["form"], "fields"):
            fk_fields = [
                f
                for f in self.model._meta.get_fields()
                if isinstance(f, ForeignKey) and f.name in context["form"].fields
            ]
            for f in fk_fields:
                try:
                    qs = f.related_model.objects.filter(user=self.request.user)
                except FieldError:  # Not a user field
                    qs = f.related_model.objects.all()
                context["form"].fields[f.name].queryset = qs
        return context


# -- ACCOUNTS --
class AccountList(LoginRequiredMixin, SingleTableView):
    model = models.CreditLine
    table_class = tables.CreditLineTable
    template_name = "debt/account-list.html"

    def get_table_data(self) -> "QuerySet":
        qs = super().get_table_data()
        return qs.filter(user=self.request.user)


class AccountView(LoginRequiredMixin, AuthQuerySetMixin, generic.DetailView):
    model = models.CreditLine
    template_name = "debt/account-detail.html"


class AccountCreate(
    LoginRequiredMixin, AuthCreateFormMixin, AuthForeignKeyMixin, CreateView
):
    model = models.CreditLine
    fields = [
        "name",
        "holder",
        "statement_date",
        "date_opened",
        "annual_fee",
        "interest_rate",
        "credit_line",
        "min_pay_pct",
        "min_pay_dlr",
        "priority",
    ]
    template_name = "debt/account-add.html"


class AccountUpdate(
    LoginRequiredMixin, AuthQuerySetMixin, AuthForeignKeyMixin, UpdateView
):
    model = models.CreditLine
    fields = [
        "name",
        "holder",
        "statement_date",
        "date_opened",
        "annual_fee",
        "interest_rate",
        "credit_line",
        "min_pay_pct",
        "min_pay_dlr",
        "priority",
    ]
    template_name = "debt/account-update.html"


class AccountDelete(LoginRequiredMixin, AuthQuerySetMixin, DeleteView):
    model = models.CreditLine
    success_url = reverse_lazy("debt:account-list")
    template_name = "debt/account-delete.html"


class CreditLineBulkUpdate(LoginRequiredMixin, generic.FormView):
    form_class = forms.CreditLineBulkUpdateForm
    success_url = reverse_lazy("debt:account-list")
    template_name = "debt/creditline-bulk-update.html"
    cols = [
        "name",
        "holder",
        "statement_date",
        "date_opened",
        "annual_fee",
        "interest_rate",
        "credit_line",
        "min_pay_pct",
        "min_pay_dlr",
        "priority",
    ]

    def form_valid(
        self, form: "forms.StatementBulkUpdateForm"
    ) -> "HttpResponseRedirect":
        # Read the CSV into a DataFrame
        path = self.request.FILES["csv"]
        try:
            df = pd.read_csv(
                path,
                usecols=self.cols,
                infer_datetime_format=True,
                parse_dates=["date_opened"],
            )
        except ValueError as e:
            messages.error(self.request, f"Restore failed: {e}")
            return self.form_invalid(form)

        # Iterate through the data
        counts = {"Existing Accounts Not Overwritten": 0, "New Accounts Added": 0}
        for __, row in df.iterrows():
            _, created = models.CreditLine.objects.get_or_create(
                user=self.request.user,
                name=row["name"],
                defaults=dict(
                    holder=row.holder,
                    statement_date=row.statement_date,
                    date_opened=row.date_opened,
                    annual_fee=row.annual_fee,
                    interest_rate=row.interest_rate,
                    credit_line=row.credit_line,
                    min_pay_pct=row.min_pay_pct,
                    min_pay_dlr=row.min_pay_dlr,
                    priority=row.priority,
                ),
            )
            if not created:
                counts["Existing Accounts Not Overwritten"] += 1
            else:
                counts["New Accounts Added"] += 1

        # Add processing info to messages
        for k, v in counts.items():
            if not v:
                continue
            messages.info(self.request, f"{k}: {v}")

        return super().form_valid(form)


# -- STATEMENTS --
class StatementCreate(
    LoginRequiredMixin, AuthCreateFormMixin, AuthForeignKeyMixin, CreateView
):
    model = models.Statement
    fields = ["account", "month", "year", "balance"]
    template_name = "debt/statement-add.html"


class StatementUpdate(
    LoginRequiredMixin, AuthQuerySetMixin, AuthForeignKeyMixin, UpdateView
):
    model = models.Statement
    fields = ["account", "month", "year", "balance"]
    template_name = "debt/statement-update.html"


class StatementDelete(LoginRequiredMixin, AuthQuerySetMixin, DeleteView):
    model = models.Statement
    success_url = reverse_lazy("debt:account-list")
    template_name = "debt/statement-delete.html"


class StatementBulkDownload(LoginRequiredMixin, generic.View):
    def get(self, *_, **__):
        timestamp = datetime.datetime.now().strftime("%y%m%d_%H%M%S")
        path = os.path.join(tempfile.mkdtemp(), f"statements_{timestamp}.csv")
        fieldnames = ["Account", "Date", "Balance"]
        qs = models.Statement.objects.filter(user=self.request.user).all()
        with open(path, "w") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            for statement in qs:
                writer.writerow(
                    dict(
                        Account=statement.account.name,
                        Date=statement.date.strftime("%Y-%m-%d"),
                        Balance=statement.balance,
                    )
                )
        return FileResponse(open(path, "rb"), as_attachment=True)


class StatementBulkUpdate(LoginRequiredMixin, generic.FormView):
    form_class = forms.StatementBulkUpdateForm
    success_url = reverse_lazy("debt:debt-summary")
    template_name = "debt/statement-bulk-update.html"

    def form_valid(
        self, form: "forms.StatementBulkUpdateForm"
    ) -> "HttpResponseRedirect":
        # Read the CSV into a DataFrame
        path = self.request.FILES["csv"]
        try:
            df = pd.read_csv(
                path,
                usecols=["Account", "Date", "Balance"],
                infer_datetime_format=True,
                parse_dates=["Date"],
            )
        except ValueError as e:
            messages.error(self.request, f"Restore failed: {e}")
            return self.form_invalid(form)

        # Validate the accounts - Use get_or_create to see if there's
        # already an account for each provided name, and raise a warning
        # if there isn't.
        acc_objs = {}  # type: Dict[str, models.CreditLine]
        for acc_name in df.Account.unique():
            acc, created = models.CreditLine.objects.get_or_create(
                user=self.request.user, name=acc_name
            )
            if created:
                messages.warning(self.request, f"Unknown credit line: {acc_name}")
                acc.delete()
            else:
                acc_objs[acc_name] = acc

        # Add columns for year and month
        # There are probably some exceptions to catch here
        df["Year"] = df["Date"].dt.year
        df["Month"] = df["Date"].dt.month

        # Iterate through the data
        counts = {
            "Unknown Accounts": 0,
            "Existing Statements Not Overwritten": 0,
            "New Statements Added": 0,
        }
        for __, row in df.iterrows():
            if row["Account"] not in acc_objs:
                counts["Unknown Accounts"] += 1
                continue
            _, created = models.Statement.objects.get_or_create(
                user=self.request.user,
                account=acc_objs[row["Account"]],
                year=row["Year"],

debt/templates/debt/account-add.html
{% extends "debt_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        New Account
    {% endblock %}
{% endblock %}

{% block content %}
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form|crispy }}
        <a type="submit">{% bootstrap_button 'Save' %}</a>
    </form>
    <a href="{% url 'debt:account-list' %}">
        {% bootstrap_button 'Back to Credit Lines' %}
    </a>
{% endblock %}

debt/templates/debt/account-delete.html
{% extends "debt_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        Delete Credit Line: {{ creditline }}
    {% endblock %}
{% endblock %}

{% block content %}
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form|crispy }}
        <a type="submit">{% bootstrap_button 'Confirm' %}</a>
    </form>
    <a href="{% url 'debt:account-detail' creditline.id %}">
        {% bootstrap_button 'Back to Credit Line' %}
    </a>
{% endblock %}

debt/templates/debt/account-detail.html
{% extends "debt_base.html" %}
{% load bootstrap3 %}

{% block content %}
    <h2>Credit Line: {{ creditline.name }}</h2>
    <h4>Details</h4>
    <b>Holder:</b> {{ creditline.holder }}<br>
    <b>Date Opened:</b> {{ creditline.date_opened }}<br>
    <b>Annual Fee:</b> {{ creditline.annual_fee }}<br>
    <b>Interest Rate (%):</b> {{ creditline.interest_rate }}<br>
    <b>Credit Line:</b> {{ creditline.credit_line }}<br>
    <b>Minimum Payment (%):</b> {{ creditline.min_pay_pct }}<br>
    <b>Minimum Payment ($):</b> {{ creditline.min_pay_dlr }}<br>
    <b>Priority:</b> {{ creditline.priority }}<br>
    <b>Available Credit:</b> {{ creditline.available_credit }}<br>
    <a href="{% url 'debt:account-update' creditline.id %}">{% bootstrap_button 'Update' %}</a>
    <a href="{% url 'debt:account-delete' creditline.id %}">{% bootstrap_button 'Delete' %}</a>
    <h4>Statements:</h4>
    {% for s in creditline.statement_set.all %}
        <a href="{% url 'debt:statement-update' s.id %}">{{ s }}</a><br>
    {% endfor %}
    <a href="{% url 'debt:statement-add' %}">{% bootstrap_button 'Add Statement' %}</a>
{% endblock %}

debt/templates/debt/account-list.html
{% extends "debt_base.html" %}
{% load render_table from django_tables2 %}
{% load bootstrap3 %}

{% block content %}
    <h2>Accounts</h2>
    <a href="{% url 'debt:account-add' %}">
        {% bootstrap_button 'Add New Account' %}
    </a>
    <a href="{% url 'debt:creditline-bulk-update' %}">
        {% bootstrap_button 'Bulk Upload New Accounts' %}
    </a>
    {% render_table table 'django_tables2/bootstrap.html' %}
{% endblock %}

debt/templates/debt/account-update.html
{% extends "debt_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        Update Credit Line: {{ creditline }}
    {% endblock %}
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <a type="submit">{% bootstrap_button 'Update' %}</a>
    </form>
    <a href="{% url 'debt:account-detail' creditline.id %}">
        {% bootstrap_button 'Back to Credit Line' %}
    </a>
{% endblock %}

debt/templates/debt/creditline-bulk-update.html
{% extends "debt_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        Upload Credit Line Data
    {% endblock %}
{% endblock %}

{% block content %}
    <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
        {{ form|crispy }}
        <a type="submit">{% bootstrap_button 'Upload' %}</a>
    </form><br>
    <a href="{% url 'debt:account-list' %}">
        {% bootstrap_button 'Back to Credit Lines' %}
    </a>
{% endblock %}

debt/templates/debt/debt_summary.html
{% extends "debt_base.html" %}
{% load render_table from django_tables2 %}
{% load bootstrap3 %}
{% block title %}
    {% block header %}
        Debt Summary
    {% endblock %}
{% endblock %}

{% block content %}
    <p>
        <b>Monthly Debt Budget:</b>
        {% if debt_budget %}
            <span>{{ debt_budget.value }} (<a href="{% url 'budget:budget-update' debt_budget.id %}">update</a>)</span>
        {% else %}
            (none specified)
        {% endif %}
    </p>
    <a href="{% url 'debt:statement-download' %}">{% bootstrap_button 'Download Data' %}</a>
    <a href="{% url 'debt:statement-bulk-update' %}">{% bootstrap_button 'Upload Data' %}</a>
    <a href="{% url 'debt:statement-bulk-delete-confirm' %}">{% bootstrap_button 'Delete All' %}</a>
    {% render_table table 'django_tables2/bootstrap.html' %}
{% endblock %}

debt/templates/debt/index.html
{% extends "debt_base.html" %}

{% block content %}
    <h2>Summary</h2>
    <p>
        <a href="{% url 'debt:debt-summary' %}">Debt Summary</a>
    </p>
{% endblock %}

debt/templates/debt/statement-add.html
{% extends "debt_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        New Statement
    {% endblock %}
{% endblock %}

{% block content %}
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form|crispy }}
        <a type="submit">{% bootstrap_button 'Save' %}</a>
    </form>
    <a href="{% url 'debt:account-list' %}">Back to Credit Lines</a>
{% endblock %}

debt/templates/debt/statement-bulk-delete.html
{% extends "debt_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        Delete All Statement Data
    {% endblock %}
{% endblock %}

{% block content %}
    <b>Are you sure?</b>
    <form action="{% url 'debt:statement-bulk-delete' %}" method="POST">{% csrf_token %}
        <a type="submit">{% bootstrap_button 'Delete All' %}</a>
    </form>
    <a href="{% url 'debt:debt-summary' %}">
        {% bootstrap_button 'Back to Summary' %}
    </a>
{% endblock %}

debt/templates/debt/statement-bulk-update.html
{% extends "debt_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        Upload Statement Data
    {% endblock %}
{% endblock %}

{% block content %}
    <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
        {{ form|crispy }}
        <a type="submit">{% bootstrap_button 'Upload' %}</a>
    </form><br>
    <a href="{% url 'debt:debt-summary' %}">
        {% bootstrap_button 'Back to Summary' %}
    </a>
{% endblock %}

debt/templates/debt/statement-delete.html
{% extends "debt_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        Delete Statement: {{ statement }}
    {% endblock %}
{% endblock %}

{% block content %}
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form|crispy }}
        <a type="submit">{% bootstrap_button 'Confirm' %}</a>
    </form>
    <a href="{% url 'debt:account-detail' statement.account.id %}">
        {% bootstrap_button 'Back to Statement' %}
    </a>
{% endblock %}

debt/templates/debt/statement-update.html
{% extends "debt_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        Update Statement
    {% endblock %}
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <a type="submit">{% bootstrap_button 'Update' %}</a>
    </form><br>
    <a href="{% url 'debt:statement-delete' statement.pk %}">{% bootstrap_button 'Delete' %}</a>
    <a href="{% url 'debt:statement-add' %}">{% bootstrap_button 'Add New Statement' %}</a>
    <a href="{% url 'debt:account-detail' statement.account_id %}">{% bootstrap_button 'Back to Credit Line' %}</a>
{% endblock %}