budget/urls.py
from django.urls import path

from budget import views

app_name = "budget"
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    # Accounts
    path("accounts/", views.AccountList.as_view(), name="account-list"),
    path("accounts/add/", views.AccountCreate.as_view(), name="account-add"),
    path("accounts/<int:pk>/", views.AccountView.as_view(), name="account-detail"),
    path(
        "accounts/<int:pk>/update/",
        views.AccountUpdate.as_view(),
        name="account-update",
    ),
    path(
        "accounts/<int:pk>/delete/",
        views.AccountDelete.as_view(),
        name="account-delete",
    ),
    # Backups
    path("backups/", views.BackupList.as_view(), name="backup-list"),
    path("backups/add/", views.BackupUpload.as_view(), name="backup-add"),
    path("backups/addnew/", views.BackupCreateNew.as_view(), name="backup-addnew"),
    path(
        "backups/purge_confirm/",
        views.BackupPurgeAllConfirm.as_view(),
        name="backup-purge-confirm",
    ),
    path("backups/purge/", views.BackupPurgeAll.as_view(), name="backup-purge"),
    path("backups/<int:pk>/", views.BackupView.as_view(), name="backup-detail"),
    path(
        "backups/<int:pk>/download/",
        views.BackupDownload.as_view(),
        name="backup-download",
    ),
    path(
        "backups/<int:pk>/delete/", views.BackupDelete.as_view(), name="backup-delete"
    ),
    path(
        "backups/<int:pk>/restore/",
        views.BackupRestore.as_view(),
        name="backup-restore",
    ),
    # Uploads
    path("uploads/", views.UploadList.as_view(), name="upload-list"),
    path("uploads/add/", views.UploadCreate.as_view(), name="upload-add"),
    path("uploads/<int:pk>/", views.UploadView.as_view(), name="upload-detail"),
    path(
        "uploads/<int:pk>/delete/", views.UploadDelete.as_view(), name="upload-delete"
    ),
    # Classes
    path("classes/<int:pk>/", views.ClassView.as_view(), name="class-detail"),
    path(
        "classes/<int:pk>/update/", views.BudgetUpdate.as_view(), name="budget-update"
    ),
    # Categories
    path("categories/add/", views.CategoryCreate.as_view(), name="category-add"),
    path("categories/<int:pk>/", views.CategoryView.as_view(), name="category-detail"),
    path(
        "categories/<int:pk>/update/",
        views.CategoryUpdate.as_view(),
        name="category-update",
    ),
    path(
        "categories/<int:pk>/delete/",
        views.CategoryDelete.as_view(),
        name="category-delete",
    ),
    # Patterns
    path("patterns/", views.PatternList.as_view(), name="pattern-list"),
    path("patterns/add/", views.PatternCreate.as_view(), name="pattern-add"),
    path("patterns/<int:pk>/", views.PatternView.as_view(), name="pattern-detail"),
    path(
        "patterns/<int:pk>/update/",
        views.PatternUpdate.as_view(),
        name="pattern-update",
    ),
    path(
        "patterns/<int:pk>/delete/",
        views.PatternDelete.as_view(),
        name="pattern-delete",
    ),
    path("patterns/classify/", views.PatternClassify.as_view(), name="classify"),
    path("patterns/declassify/", views.PatternDeclassify.as_view(), name="declassify"),
    path(
        "patterns/upload/",
        views.PatternBulkUpdate.as_view(),
        name="pattern-bulk-update",
    ),
    # Transactions
    path("transactions/", views.TransactionList.as_view(), name="transaction-list"),
    path(
        "transactions/<int:pk>/",
        views.TransactionView.as_view(),
        name="transaction-detail",
    ),
    path(
        "transactions/<int:pk>/delete/",
        views.TransactionDelete.as_view(),
        name="transaction-delete",
    ),
]

debt/urls.py
from django.urls import path

from debt import views

app_name = "debt"
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    # Accounts
    path("accounts/", views.AccountList.as_view(), name="account-list"),
    path("accounts/add/", views.AccountCreate.as_view(), name="account-add"),
    path("accounts/<int:pk>/", views.AccountView.as_view(), name="account-detail"),
    path(
        "accounts/<int:pk>/update/",
        views.AccountUpdate.as_view(),
        name="account-update",
    ),
    path(
        "accounts/<int:pk>/delete/",
        views.AccountDelete.as_view(),
        name="account-delete",
    ),
    path(
        "accounts/upload/",
        views.CreditLineBulkUpdate.as_view(),
        name="creditline-bulk-update",
    ),
    # Statements
    path("statements/add/", views.StatementCreate.as_view(), name="statement-add"),
    path(
        "statements/download/",
        views.StatementBulkDownload.as_view(),
        name="statement-download",
    ),
    path(
        "statements/upload/",
        views.StatementBulkUpdate.as_view(),
        name="statement-bulk-update",
    ),
    path(
        "statements/delete/confirm",
        views.StatementBulkDeleteConfirm.as_view(),
        name="statement-bulk-delete-confirm",
    ),
    path(
        "statements/delete/",
        views.StatementBulkDelete.as_view(),
        name="statement-bulk-delete",
    ),
    path(
        "statements/<int:pk>/update/",
        views.StatementUpdate.as_view(),
        name="statement-update",
    ),
    path(
        "statements/<int:pk>/delete/",
        views.StatementDelete.as_view(),
        name="statement-delete",
    ),
    # Summaries
    path("summaries/debt", views.DebtSummary.as_view(), name="debt-summary"),
]

simplefi/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(url="budget/", permanent=False), name="index"),
    path("auth/", include("django_registration.backends.activation.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("budget/", include("budget.urls")),
    path("debt/", include("debt.urls")),
    path("admin/", admin.site.urls),
]

budget/forms.py
from typing import TYPE_CHECKING

from django import forms

from budget.models import Pattern

if TYPE_CHECKING:
    from budget.models import Category


class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()


class CategoryClassChoiceField(forms.ModelChoiceField):
    """Use this to show class with categories in a drop-down."""

    def label_from_instance(self, obj: "Category") -> str:
        return f"{obj.class_field} - {obj.name}"


class PatternForm(forms.ModelForm):
    class Meta:
        model = Pattern
        fields = ["pattern", "category"]
        field_classes = {"category": CategoryClassChoiceField}


class PatternBulkUpdateForm(forms.Form):
    csv = forms.FileField()

budget/views.py
import datetime
from abc import abstractmethod
from typing import TYPE_CHECKING, Any, Callable, Dict, List, Tuple, Union

import pandas as pd
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import FieldError
from django.db.models import ForeignKey
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic import DetailView, FormView, RedirectView, TemplateView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django_filters.views import FilterMixin, FilterView
from django_tables2 import Column, Table
from django_tables2.views import SingleTableMixin, SingleTableView

from budget import forms, models, tables
from budget.utils import first_day_month_after, oys_qs, thirteen_months_ago

if TYPE_CHECKING:
    from django.db.models.query import QuerySet
    from django.forms import Form
    from django.http import FileResponse

    from budget.models import Budget


class Index(LoginRequiredMixin, SingleTableView):
    template_name = "budget/index.html"
    table_class = tables.SummaryTable

    def get_queryset(self) -> List[Dict[str, Union[str, int]]]:
        qs = oys_qs(user=self.request.user)
        return qs

    def get_table_kwargs(self) -> Dict[str, List[Tuple[str, "Column"]]]:
        fmt = "%b_%y"
        orig = thirteen_months_ago()
        first = datetime.date(year=orig.year, month=orig.month, day=1)
        now = timezone.now()
        last = datetime.date(year=now.year, month=now.month, day=1)

        # Add each month to the header
        cols = []
        cur = first
        while cur <= last:
            cols.append(cur.strftime(fmt))
            cur = first_day_month_after(cur)

        extra_cols = [(c, Column(attrs={"td": dict(align="right")})) for c in cols]
        return dict(extra_columns=extra_cols)


class AuthQuerySetMixin:
    """A mixin for generic display views for user data.

    Restricts the queryset to user-associated data only.
    """

    model = None
    request = None

    def get_queryset(self) -> "QuerySet":
        return self.model.objects.filter(user=self.request.user)


class AuthCreateFormMixin:
    """A mixin for generic create views for user data.

    Automatically assigns the logged-in user to the 'user' field of the
    model.
    """

    request = None

    def form_valid(self, form: "Form") -> bool:
        form.instance.user = self.request.user
        return super().form_valid(form)


class AuthForeignKeyMixin:
    """A mixin for generic edit views to protect other users' data.

    Restricts the queryset for all foreign key fields to user-
    associated data only.
    """

    model = None
    request = None

    def get_context_data(self, **kwargs) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        if "form" in context and hasattr(context["form"], "fields"):
            fk_fields = [
                f
                for f in self.model._meta.get_fields()
                if isinstance(f, ForeignKey) and f.name in context["form"].fields
            ]
            for f in fk_fields:
                try:
                    qs = f.related_model.objects.filter(user=self.request.user)
                except FieldError:  # Not a user field
                    qs = f.related_model.objects.all()
                context["form"].fields[f.name].queryset = qs
        return context


class TransactionTableMixin(SingleTableMixin, FilterMixin):
    """A mixin for including a table of transactions in a view."""

    table_class = tables.TransactionTable
    table_pagination = dict(per_page=15)

    @abstractmethod
    def exclude_cols(self, *_, **__) -> Tuple[str, ...]:
        """Columns to exclude from the table."""

    @abstractmethod
    def get_filter_kwargs(self, *_, **__) -> Dict[str, Any]:
        """Arguments to pass to the QuerySet filter on Transactions."""

    def get_table_data(self, *args, **kwargs) -> "QuerySet":
        kwargs = self.get_filter_kwargs(*args, **kwargs)
        return models.Transaction.objects.filter(**kwargs)

    def get_table_kwargs(self, *args, **kwargs) -> Dict[str, Any]:
        d = super().get_table_kwargs()
        exclude_cols = self.exclude_cols(*args, **kwargs)
        if exclude_cols:
            d["exclude"] = exclude_cols
        return d


# -- ACCOUNTS --
class AccountList(LoginRequiredMixin, SingleTableView):
    model = models.Account
    table_class = tables.AccountTable
    template_name = "budget/account-list.html"

    def get_table_data(self) -> "QuerySet":
        qs = super().get_table_data()
        return qs.filter(user=self.request.user)


class AccountView(LoginRequiredMixin, TransactionTableMixin, DetailView):
    model = models.Account
    template_name = "budget/account-detail.html"

    def exclude_cols(self) -> Tuple[str, ...]:  # pylint: disable=arguments-differ
        return tuple(["account"])

    def get_filter_kwargs(self) -> Dict[str, Any]:  # pylint: disable=arguments-differ
        return dict(user=self.request.user, upload__account=self.object)


class AccountCreate(
    LoginRequiredMixin, AuthCreateFormMixin, AuthForeignKeyMixin, CreateView
):
    model = models.Account
    fields = ["name", "date_col_name", "amt_col_name", "desc_col_name"]
    template_name = "budget/account-add.html"


class AccountUpdate(
    LoginRequiredMixin, AuthQuerySetMixin, AuthForeignKeyMixin, UpdateView
):
    model = models.Account
    fields = ["name", "date_col_name", "amt_col_name", "desc_col_name"]
    template_name = "budget/account-update.html"


class AccountDelete(LoginRequiredMixin, AuthQuerySetMixin, DeleteView):
    model = models.Account
    success_url = reverse_lazy("budget:account-list")
    template_name = "budget/account-delete.html"


# -- CSV BACKUPS --
class BackupList(LoginRequiredMixin, SingleTableView):
    model = models.CSVBackup
    table_class = tables.BackupTable
    template_name = "budget/backup-list.html"

    def get_table_data(self) -> "QuerySet":
        qs = super().get_table_data()
        return qs.filter(user=self.request.user)


class BackupUpload(
    LoginRequiredMixin, AuthCreateFormMixin, AuthForeignKeyMixin, CreateView
):
    """Upload a CSV for restore."""

    model = models.CSVBackup
    fields = ["csv"]
    template_name = "budget/backup-add.html"


class BackupCreateNew(LoginRequiredMixin, View):
    """Create a new backup from current transaction data."""

    def post(self, *_, **__) -> "HttpResponseRedirect":
        backup = models.CSVBackup(user=self.request.user)
        backup.create_backup()
        return HttpResponseRedirect(reverse_lazy("budget:backup-list"))


class BackupPurgeAllConfirm(LoginRequiredMixin, TemplateView):
    """A splash page with a button to purge all transactions."""

    template_name = "budget/backup-purge-confirm.html"


class BackupPurgeAll(LoginRequiredMixin, View):
    """Purges all transactions."""

    def post(self, *_, **__) -> "HttpResponseRedirect":
        models.Transaction.objects.filter(user=self.request.user).delete()
        return HttpResponseRedirect(reverse_lazy("budget:backup-list"))


class BackupView(LoginRequiredMixin, DetailView):
    model = models.CSVBackup
    template_name = "budget/backup-detail.html"


class BackupDownload(LoginRequiredMixin, SingleObjectMixin, View):
    """Gets the file response for a backup."""

    def get(self, *_, **__) -> "FileResponse":
        return self.get_object(
            queryset=models.CSVBackup.objects.filter(user=self.request.user)
        ).file_response()


class BackupRestore(LoginRequiredMixin, SingleObjectMixin, View):
    """Restores transactions from a backup."""

    def post(self, *_, **__) -> "HttpResponseRedirect":
        obj = self.get_object(
            queryset=models.CSVBackup.objects.filter(user=self.request.user)
        )  # type: models.CSVBackup
        msg = obj.restore()
        if msg != obj.SUCCESS_CODE:
            messages.error(self.request, f"Restore failed: {msg}")

        return HttpResponseRedirect(reverse_lazy("budget:backup-list"))


class BackupDelete(LoginRequiredMixin, AuthQuerySetMixin, DeleteView):
    model = models.CSVBackup
    success_url = reverse_lazy("budget:backup-list")
    template_name = "budget/backup-delete.html"


# -- UPLOADS --
class UploadList(LoginRequiredMixin, SingleTableView):
    model = models.Upload
    table_class = tables.UploadTable
    template_name = "budget/upload-list.html"

    def get_table_data(self) -> "QuerySet":
        qs = super().get_table_data()
        return qs.filter(user=self.request.user)


class UploadView(LoginRequiredMixin, TransactionTableMixin, DetailView):
    model = models.Upload
    template_name = "budget/upload-detail.html"

    def exclude_cols(self) -> Tuple[str, ...]:  # pylint: disable=arguments-differ
        return "account", "upload"

    def get_filter_kwargs(self) -> Dict[str, Any]:  # pylint: disable=arguments-differ
        return dict(user=self.request.user, upload=self.object)


class UploadCreate(LoginRequiredMixin, AuthForeignKeyMixin, CreateView):
    model = models.Upload
    fields = ["account", "csv"]
    template_name = "budget/upload-add.html"

    def form_valid(self, form: "Form") -> "HttpResponseRedirect":
        form.instance.user = self.request.user
        self.object = form.save()  # pylint: disable=attribute-defined-outside-init

        msg = self.object.parse_transactions()
        if msg == self.model.SUCCESS_CODE:
            # Add transactions after saving, before redirecting
            url = self.get_success_url()
        else:
            # This should redirect to a page showing the error mesage instead
            self.object.delete()
            messages.error(self.request, f"Upload failed: {msg}")

budget/templates/budget/account-add.html
{% extends "budget_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        New Account
    {% endblock %}
{% endblock %}

{% block content %}
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form|crispy }}
        <a type="submit">{% bootstrap_button 'Save' %}</a>
    </form><br>
    <a href="{% url 'budget:account-list' %}">{% bootstrap_button 'Back to Account List' %}</a>
{% endblock %}

budget/templates/budget/backup-add.html
{% extends "budget_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        New Backup
    {% endblock %}
{% endblock %}

{% block content %}
    <form action="" method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
        {{ form|crispy }}
        <a type="submit">{% bootstrap_button 'Save' %}</a>
    </form><br>
    <a href="{% url 'budget:backup-list' %}">{% bootstrap_button 'Back to Backup List' %}</a>
{% endblock %}

budget/templates/budget/backup-purge-confirm.html
{% extends "budget_base.html" %}
{% load render_table from django_tables2 %}
{% load bootstrap3 %}
{% block title %}
    {% block header %}
        Are you sure?
    {% endblock %}
{% endblock %}

{% block content %}
    <p>
    Pressing the button below will clear all your transaction data from
    the server. Make sure you've already created a backup
    <a href="{% url 'budget:backup-list' %}">here</a>.
    </p>
  <form action="{% url 'budget:backup-purge' %}" method="post" class="form form-group">
    {% csrf_token %}
    {% bootstrap_button 'Clear All Data' %}
  </form>
{% endblock %}

budget/templates/budget/budget-update.html
{% extends "budget_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        Update {{ budget.class_field.name|title }} Budget
    {% endblock %}
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <a type="submit">{% bootstrap_button 'Update' %}</a>
    </form><br>
    <a href="{% url 'budget:index' %}">{% bootstrap_button "Back to Summary" %}</a>
{% endblock %}

budget/templates/budget/category-add.html
{% extends "budget_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        New Category
    {% endblock %}
{% endblock %}

{% block content %}
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form|crispy }}
        <a type="submit">{% bootstrap_button 'Save' %}</a>
    </form>
{% endblock %}

budget/templates/budget/category-delete.html
{% extends "budget_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        Delete Category: {{ category }}
    {% endblock %}
{% endblock %}

{% block content %}
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form|crispy }}
        <a type="submit">{% bootstrap_button 'Confirm' %}</a>
    </form>
    <a href="{% url 'budget:category-detail' category.id %}">{% bootstrap_button "Back to Category: "|add:category.name %}</a>
{% endblock %}

budget/templates/budget/class-detail.html
{% extends "budget_base.html" %}
{% load render_table from django_tables2 %}
{% load bootstrap3 %}
{% block title %}
    {% block header %}
        Class Detail: {{ transactionclass }}
    {% endblock %}
{% endblock %}

{% block content %}
    {% if view.budget %}
    <p>
        <b>Budget:</b>
        {{ view.budget.value }} (<a href="{% url 'budget:budget-update' view.budget.id %}">update</a>)
    </p>
    {% endif %}
    <a href="{% url 'budget:index' %}">{% bootstrap_button 'Back To Summary' %}</a>

    {% if view.categories %}
    <h3>One-Year Summary</h3>
    <a href="{% url 'budget:category-add' %}">
        {% bootstrap_button 'Add New Category' %}
    </a>
    {% render_table table 'django_tables2/bootstrap.html' %}
    {% endif %}
{% endblock %}

budget/templates/budget/pattern-bulk-update.html
{% extends "budget_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        Upload Patterns
    {% endblock %}
{% endblock %}

{% block content %}
    <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
        {{ form|crispy }}
        <a type="submit">{% bootstrap_button 'Upload' %}</a>
    </form><br>
    <a href="{% url 'budget:pattern-list' %}">{% bootstrap_button 'Back to Patterns' %}</a>
{% endblock %}

budget/templates/budget/pattern-delete.html
{% extends "budget_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        Delete Pattern: {{ pattern }}
    {% endblock %}
{% endblock %}

{% block content %}
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form|crispy }}
        <a type="submit">{% bootstrap_button 'Confirm' %}</a>
    </form>
    <a href="{% url 'budget:pattern-detail' pattern.id %}">
        {% bootstrap_button 'Back to Pattern' %}
    </a>
{% endblock %}

budget/templates/budget/pattern-detail.html
{% extends "budget_base.html" %}
{% load render_table from django_tables2 %}
{% load bootstrap3 %}
{% block title %}
    {% block header %}
        Pattern Detail: {{ pattern.pattern }}
    {% endblock %}
{% endblock %}

{% block content %}
    <h4>Details</h4>
    <b>Class:</b>
        <a href="{% url 'budget:class-detail' pattern.class_field.id %}">
            {{ pattern.class_field }}
        </a>
        <br>
    <b>Category:</b>
        <a href="{% url 'budget:category-detail' pattern.category.id %}">
            {{ pattern.category }}
        </a>
        <br>
    <a href="{% url 'budget:pattern-update' pattern.id %}">{% bootstrap_button 'Update' %}</a>
    <a href="{% url 'budget:pattern-delete' pattern.id %}">{% bootstrap_button 'Delete' %}</a>

    <h4>Transactions</h4>
    {% render_table table 'django_tables2/bootstrap.html' %}

{% endblock %}

budget/templates/budget/pattern-list.html
{% extends "budget_base.html" %}
{% load render_table from django_tables2 %}
{% load bootstrap3 %}
{% block title %}
    {% block header %}
        Patterns
    {% endblock %}
{% endblock %}

{% block content %}
    {# -- UNMATCHED TRANSACTIONS -- #}
    <p><b>Unmatched transactions: {{ num_unmatched_transactions }}</b></p>
    <ul>
        {% for t in unmatched_transaction_list %}
            <li><a href="{% url 'budget:transaction-detail' t.id %}">{{ t }}</a></li>
        {% endfor %}
    </ul>

    {# -- BUTTONS -- #}
    <a href="{% url 'budget:declassify' %}">{% bootstrap_button 'Declassify All' %}</a>
    <a href="{% url 'budget:classify' %}">{% bootstrap_button 'Classify' %}</a>
    <a href="{% url 'budget:pattern-add' %}">{% bootstrap_button 'Add New Pattern' %}</a>
    <a href="{% url 'budget:pattern-bulk-update' %}">{% bootstrap_button 'Upload Patterns' %}</a>

    {# -- PATTERN LIST -- #}
    <div class="container-fluid">
        <div class="row">
          <div class="col-sm-8">
            {% render_table table 'django_tables2/bootstrap.html' %}
          </div>
          <div class="col-sm-4">
            {% if filter %}
              <form action="" method="get" class="form form-group">
                {% bootstrap_form filter.form layout='horizontal' size='small' %}
                {% bootstrap_button 'Filter' %}
              </form>
              <a href="{% url 'budget:pattern-list' %}">
                {% bootstrap_button 'Clear' %}
              </a>
            {% endif %}
          </div>
        </div>
      </div>
{% endblock %}

budget/templates/budget/transaction-list.html
{% extends "budget_base.html" %}
{% load render_table from django_tables2 %}
{% load bootstrap3 %}
{% block title %}
    {% block header %}
        Transactions
    {% endblock %}
{% endblock %}

{% block content %}
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-8">
        {% render_table table 'django_tables2/bootstrap.html' %}
      </div>
      <div class="col-sm-4">
        {% if filter %}
          <form action="" method="get" class="form form-group">
            {% bootstrap_form filter.form layout='horizontal' size='small' %}
            {% bootstrap_button 'Filter' %}
          </form>
          <a href="{% url 'budget:transaction-list' %}">
            {% bootstrap_button 'Clear' %}
          </a>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock %}

budget/templates/budget/upload-add.html
{% extends "budget_base.html" %}
{% load bootstrap3 %}
{% load crispy_forms_tags %}
{% block title %}
    {% block header %}
        New Upload
    {% endblock %}
{% endblock %}

{% block content %}
    <form action="" method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
        {{ form|crispy }}
        <a type="submit">{% bootstrap_button 'Save' %}</a>
    </form><br>
    <a href="{% url 'budget:upload-list' %}">{% bootstrap_button 'Back to Upload List' %}</a>
{% endblock %}

budget/templates/budget/upload-detail.html
{% extends "budget_base.html" %}
{% load static %}
{% load render_table from django_tables2 %}
{% load bootstrap3 %}
{% block header %}
    {% block title %}
    Upload: {{ upload }}
{% endblock %}
    (<a href="{% url 'budget:account-detail' upload.account.id %}">{{ upload.account }}</a>)
{% endblock %}

{% block content %}
    <a href="{{ upload.csv.url }}">{% bootstrap_button 'View CSV' %}</a>
    <a href="{% url 'budget:upload-delete' upload.id %}">{% bootstrap_button 'Delete' %}</a>
    <a href="{% url 'budget:upload-add' %}">{% bootstrap_button 'Add New Upload' %}</a>
    <h4>Transactions</h4>
    {% render_table table 'django_tables2/bootstrap.html' %}
{% endblock %}