budget/urls.py
from django.urls import path

from budget import views

app_name = "budget"
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    # Accounts
    path("accounts/", views.AccountList.as_view(), name="account-list"),
    path("accounts/add/", views.AccountCreate.as_view(), name="account-add"),
    path("accounts/<int:pk>/", views.AccountView.as_view(), name="account-detail"),
    path(
        "accounts/<int:pk>/update/",
        views.AccountUpdate.as_view(),
        name="account-update",
    ),
    path(
        "accounts/<int:pk>/delete/",
        views.AccountDelete.as_view(),
        name="account-delete",
    ),
    # Backups
    path("backups/", views.BackupList.as_view(), name="backup-list"),
    path("backups/add/", views.BackupUpload.as_view(), name="backup-add"),
    path("backups/addnew/", views.BackupCreateNew.as_view(), name="backup-addnew"),
    path(
        "backups/purge_confirm/",
        views.BackupPurgeAllConfirm.as_view(),
        name="backup-purge-confirm",
    ),
    path("backups/purge/", views.BackupPurgeAll.as_view(), name="backup-purge"),
    path("backups/<int:pk>/", views.BackupView.as_view(), name="backup-detail"),
    path(
        "backups/<int:pk>/download/",
        views.BackupDownload.as_view(),
        name="backup-download",
    ),
    path(
        "backups/<int:pk>/delete/", views.BackupDelete.as_view(), name="backup-delete"
    ),
    path(
        "backups/<int:pk>/restore/",
        views.BackupRestore.as_view(),
        name="backup-restore",
    ),
    # Uploads
    path("uploads/", views.UploadList.as_view(), name="upload-list"),
    path("uploads/add/", views.UploadCreate.as_view(), name="upload-add"),
    path("uploads/<int:pk>/", views.UploadView.as_view(), name="upload-detail"),
    path(
        "uploads/<int:pk>/delete/", views.UploadDelete.as_view(), name="upload-delete"
    ),
    # Classes
    path("classes/<int:pk>/", views.ClassView.as_view(), name="class-detail"),
    path(
        "classes/<int:pk>/update/", views.BudgetUpdate.as_view(), name="budget-update"
    ),
    # Categories
    path("categories/add/", views.CategoryCreate.as_view(), name="category-add"),
    path("categories/<int:pk>/", views.CategoryView.as_view(), name="category-detail"),
    path(
        "categories/<int:pk>/update/",
        views.CategoryUpdate.as_view(),
        name="category-update",
    ),
    path(
        "categories/<int:pk>/delete/",
        views.CategoryDelete.as_view(),
        name="category-delete",
    ),
    # Patterns
    path("patterns/", views.PatternList.as_view(), name="pattern-list"),
    path("patterns/add/", views.PatternCreate.as_view(), name="pattern-add"),
    path("patterns/<int:pk>/", views.PatternView.as_view(), name="pattern-detail"),
    path(
        "patterns/<int:pk>/update/",
        views.PatternUpdate.as_view(),
        name="pattern-update",
    ),
    path(
        "patterns/<int:pk>/delete/",
        views.PatternDelete.as_view(),
        name="pattern-delete",
    ),
    path("patterns/classify/", views.PatternClassify.as_view(), name="classify"),
    path("patterns/declassify/", views.PatternDeclassify.as_view(), name="declassify"),
    path(
        "patterns/upload/",
        views.PatternBulkUpdate.as_view(),
        name="pattern-bulk-update",
    ),
    # Transactions
    path("transactions/", views.TransactionList.as_view(), name="transaction-list"),
    path(
        "transactions/<int:pk>/",
        views.TransactionView.as_view(),
        name="transaction-detail",
    ),
    path(
        "transactions/<int:pk>/delete/",
        views.TransactionDelete.as_view(),
        name="transaction-delete",
    ),
]

debt/urls.py
from django.urls import path

from debt import views

app_name = "debt"
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    # Accounts
    path("accounts/", views.AccountList.as_view(), name="account-list"),
    path("accounts/add/", views.AccountCreate.as_view(), name="account-add"),
    path("accounts/<int:pk>/", views.AccountView.as_view(), name="account-detail"),
    path(
        "accounts/<int:pk>/update/",
        views.AccountUpdate.as_view(),
        name="account-update",
    ),
    path(
        "accounts/<int:pk>/delete/",
        views.AccountDelete.as_view(),
        name="account-delete",
    ),
    path(
        "accounts/upload/",
        views.CreditLineBulkUpdate.as_view(),
        name="creditline-bulk-update",
    ),
    # Statements
    path("statements/add/", views.StatementCreate.as_view(), name="statement-add"),
    path(
        "statements/download/",
        views.StatementBulkDownload.as_view(),
        name="statement-download",
    ),
    path(
        "statements/upload/",
        views.StatementBulkUpdate.as_view(),
        name="statement-bulk-update",
    ),
    path(
        "statements/delete/confirm",
        views.StatementBulkDeleteConfirm.as_view(),
        name="statement-bulk-delete-confirm",
    ),
    path(
        "statements/delete/",
        views.StatementBulkDelete.as_view(),
        name="statement-bulk-delete",
    ),
    path(
        "statements/<int:pk>/update/",
        views.StatementUpdate.as_view(),
        name="statement-update",
    ),
    path(
        "statements/<int:pk>/delete/",
        views.StatementDelete.as_view(),
        name="statement-delete",
    ),
    # Summaries
    path("summaries/debt", views.DebtSummary.as_view(), name="debt-summary"),
]

simplefi/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

urlpatterns = [
    path("", RedirectView.as_view(url="budget/", permanent=False), name="index"),
    path("auth/", include("django_registration.backends.activation.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("budget/", include("budget.urls")),
    path("debt/", include("debt.urls")),
    path("admin/", admin.site.urls),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}Home{% endblock %} - SimpleFi</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

    <!-- Add additional CSS/JS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'style.css' %}?id=2234">
  <script src="{% static 'main.js' %}"></script>
</head>
<body>
  <nav class="simplefi-navbar">
    <a href="#">SimpleFi</a>
    {% if user.is_authenticated %}
    <div class="simplefi-dropdown">
        <button class="simplefi-dropbtn">Budget
          <i class="fa fa-caret-down"></i>
        </button>
        <div class="simplefi-dropdown-content">
            <a href="{% url 'budget:index' %}">Summary</a>
            <a href="{% url 'budget:account-list' %}">Accounts</a>
            <a href="{% url 'budget:backup-list' %}">Backups</a>
            <a href="{% url 'budget:upload-list' %}">Uploads</a>
            <a href="{% url 'budget:pattern-list' %}">Patterns</a>
            <a href="{% url 'budget:transaction-list' %}">Transactions</a>
        </div>
    </div>
    <div class="simplefi-dropdown">
        <button class="simplefi-dropbtn">Debt
          <i class="fa fa-caret-down"></i>
        </button>
        <div class="simplefi-dropdown-content">
            <a href="{% url 'debt:index' %}">Summary</a>
            <a href="{% url 'debt:account-list' %}">Credit Lines</a>
        </div>
    </div>
    <a href="{% url 'logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'login' %}">Login</a>
    <a href="{% url 'django_registration_register' %}">Sign Up</a>
    {% endif %}
  </nav>
  <div class="container-fluid">
    <div class="row">
        <div class="msgbox">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  <a class="close" href="#" data-dismiss="alert">×</a>
                  {{ message }}
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="row">
      <div id="main" class="main">
        <h2>{% block header %}{% endblock %}</h2>
        {% block content %}{% endblock %}
      </div>
    </div>
  </div>
</body>
</html>